"use strict";
const $=id=>document.getElementById(id);let lastReceipt=null;let busy=false;
function element(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
async function post(path,data){const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const r=await response.json();if(!response.ok)throw new Error(r.error||"Request failed");return r;}
async function status(){try{const r=await(await fetch('/api/status')).json();$('live-run').disabled=!r.nebius_key_configured||busy;$('provider-state').textContent=r.nebius_key_configured?'Nebius key configured':'Live provider needs a key';$('access-note').textContent=r.nebius_key_configured?'The live run selects an available NVIDIA model from Token Factory. At most two model calls, 900 output tokens each.':'Set NEBIUS_API_KEY on the server for a real NVIDIA run. The labelled control checks the software; it does not qualify as a live model integration.';}catch{$('provider-state').textContent='Local server unavailable';}}
function render(events){$('timeline').replaceChildren();for(const e of events){const node=element('article',undefined,'event'+(e.phase==='model_request'?' request':''));const top=element('div',undefined,'event-top');top.append(element('span',`STEP ${String(e.event_id).padStart(2,'0')} · ${e.phase.replaceAll('_',' ').toUpperCase()}`,'tag'));if(e.status)top.append(element('span',e.status==='REFUTED'?'× REFUTED':e.status.startsWith('CERTIFIED')?'✓ CHECKED':e.status,'verdict'+(e.status==='REFUTED'?' bad':'')));node.append(top);
if(e.phase==='seed_check'){node.append(element('h3','The first guess fails.'));node.append(element('p','An exact admissible state changes x+y under the declared map.'));}
else if(e.phase==='model_request'){node.append(element('h3',e.live?'Ask NVIDIA to revise the hypothesis.':'Run the deterministic control proposer.'));node.append(element('p',e.live?'The request carries the actual counterexample from the checking kernel.':'This is explicitly a software control, not a NVIDIA model call.'));}
else if(e.phase==='proposal_check'){node.append(element('h3',e.status.startsWith('CERTIFIED')?'A conserved quantity survives.':'Keep the feedback. Revise the hypothesis.'));if(e.proposal)node.append(element('p',e.proposal.motivation));}
else if(e.phase==='provider_error'){node.append(element('h3','The live provider could not finish.'));node.append(element('p',e.reason));}
if(e.proposal)node.append(element('code',`H = (${e.proposal.numerator}) / (${e.proposal.denominator})`));const p=e.verification?.counterexample;if(p)node.append(element('div','Counterexample: '+Object.entries(p).map(([k,v])=>`${k}=${v}`).join(', '),'counterexample'));if(e.verification?.domain_nonzero_guard_count)node.append(element('p',e.status==='CERTIFIED_RATIONAL_INVARIANT'?`The certificate retains ${e.verification.domain_nonzero_guard_count} nonzero domain guards. The checked identity is uniform in the fixed parameter.`:`The checking obligation retains ${e.verification.domain_nonzero_guard_count} nonzero domain guard. The exact counterexample belongs to the declared domain.`));$('timeline').append(node);}}
async function start(provider){if(busy)return;busy=true;$('control-run').disabled=true;$('live-run').disabled=true;$('receipt-section').hidden=true;$('mode-badge').textContent=provider==='control'?'DETERMINISTIC CONTROL':'LIVE NVIDIA';$('mode-badge').className='mode-badge'+(provider==='control'?' control':'');$('activity').textContent='Starting the exact seed check…';try{const {job_id}=await post('/api/research',{provider,rounds:2});let job;while(true){job=await(await fetch('/api/jobs/'+job_id)).json();render(job.events||[]);if(job.status!=='running')break;$('activity').textContent='The proposal is being checked. The log retains failed statements.';await new Promise(r=>setTimeout(r,400));}if(job.status==='error')throw new Error(job.error);lastReceipt=job.receipt;$('receipt-section').hidden=false;$('receipt-id').textContent=lastReceipt.receipt_id;$('evidence-json').textContent=JSON.stringify(lastReceipt,null,2);$('activity').textContent=lastReceipt.status==='CERTIFIED_RESULT'?'The supported identity is certified. Mathematical evidence is ready for replay.':'No certified result was obtained. The failure evidence was retained.';}catch(error){$('activity').textContent=error.message;}finally{busy=false;$('control-run').disabled=false;status();}}
$('control-run').addEventListener('click',()=>start('control'));$('live-run').addEventListener('click',()=>start('nebius'));$('replay').addEventListener('click',async()=>{try{const r=await post('/api/replay',{receipt:lastReceipt});$('activity').textContent=`Replay passed: ${r.mathematical_checks} mathematical checks. The model was not called again.`;}catch(e){$('activity').textContent=e.message;}});$('download').addEventListener('click',()=>{if(!lastReceipt)return;const url=URL.createObjectURL(new Blob([JSON.stringify(lastReceipt,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='noetherpilot-'+lastReceipt.receipt_id.slice(0,12)+'.json';a.click();URL.revokeObjectURL(url);});status();
